<#
.SYNOPSIS
  Starts Docker Engine in WSL and launches POS server containers.
  Auto-generated by setup-pos.ps1 -- edit the paths below or re-run setup-pos.ps1 to regenerate.
#>

$WslDistro    = "Ubuntu"       # WSL distro name
$ProjectDir   = "~/POS"        # path inside WSL to the project

Write-Host "Starting Docker Engine in WSL ($WslDistro)..." -ForegroundColor Cyan

wsl -d $WslDistro -- sudo service docker start
if ($LASTEXITCODE -ne 0) {
    Write-Host "! Failed to start Docker. Is Docker Engine installed in WSL?" -ForegroundColor Red
    exit 1
}

Write-Host "Waiting for Docker daemon..." -ForegroundColor Cyan
Start-Sleep 3

Write-Host "Launching POS containers..." -ForegroundColor Cyan
wsl -d $WslDistro -- docker compose -f "$ProjectDir/docker-compose.yml" up -d

if ($LASTEXITCODE -eq 0) {
    Write-Host "[+] POS server containers are running" -ForegroundColor Green
} else {
    Write-Host "! Failed to start containers. Check your .env and project path." -ForegroundColor Red
}
